#!/bin/bash

# sysinfo - Un script que informa del estado del sistema


##### Constantes


TITLE="Información del sistema para $HOSTNAME"
RIGHT_NOW=$(date +"%x %r%Z")
TIME_STAMP="Actualizada el $RIGHT_NOW por $USER"

##### Estilos

TEXT_BOLD=$(tput bold)
TEXT_GREEN=$(tput setaf 2)
TEXT_RESET=$(tput sgr0)
TEXT_ULINE=$(tput sgr 0 1)

##### Funciones

system_info()
{
    echo "${TEXT_ULINE}Tiempo de encendido del sistema${TEXT_RESET}"
    echo
    uptime
    echo
}


show_uptime()
{
    echo "${TEXT_ULINE}Versión del sistema${TEXT_RESET}"
    echo
    uname -a
    echo
}


drive_space()
{
    echo "${TEXT_ULINE}Espacio ocupado en las particiones/discos duros del sistema${TEXT_RESET}"
    echo
    df -h | awk '{print $1,$2,$4}' | column -t -s ' '
    echo
}


home_space()
{
    echo "${TEXT_ULINE}Espacio ocupado por cada uno de los subdirectorios${TEXT_RESET}"
    echo
    if [ "$USER" == root ]; then
        du -sh /home/* | sort -rh
    else    
        du -sh /home/$USER
    fi
    echo
}

##### Programa principal

cat << _EOF_
$TEXT_BOLD$TITLE$TEXT_RESET

$TEXT_GREEN$TIME_STAMP$TEXT_RESET
_EOF_

system_info
show_uptime
drive_space
home_space
