#!/bin/bash

# funcion usage para mostrar como se debe usar el prgrama
function usage() {
    echo "Usage: scdebug [-h] [-sto arg] [-v | -vall] [-nattch progtoattach] [prog [arg1 ...]]"
    echo "-h         Muestra esta salida de texto para ayudar."
    echo "-sto arg   Strace options con mas argumentos."
    echo "-nattch progtoattach   Hace un attach al programa indicado."
    exit 1
}

# Crea un directorio en acso de que no exista
function create_dir() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi
}

strace_options=""
attach_program=""
program=""
args=()
while [ "$#" -gt 0 ]; do
    case "$1" in
        -sto)
            shift
            strace_options="$1"
            ;;

        -nattch)
            shift
            attach_program="$1"
            ;;
        -h)
            usage
            ;;
        *)
            if [ -z "$program" ]; then
                program="$1"
            else
                args+=("$1")
            fi
            ;;
    esac
    shift
done

# identificador unico para los txt
uuid=$(uuidgen)

# camino al directorio y nombre del txt
trace_dir=".scdebug/$program"
trace_file="$trace_dir/trace_$uuid.txt"

# se crea el directorio si no existe
create_dir "$trace_dir"

# Si se hace el attach a un programa, se busca el mas reciente
if [ -n "$attach_program" ]; then
    pid=$(pgrep -n "$attach_program")
    if [ -z "$pid" ]; then
        echo "No running process found with name: $attach_program"
        exit 1
    fi
    strace_command="strace $strace_options -p $pid -o $trace_file"
else
    strace_command="strace $strace_options -o $trace_file $program ${args[@]}"
fi

# ejecutamos en segundo plano
$strace_command &

echo "strace command is running in the background."
echo "Trace file: $trace_file"
